server:
 port: 8081 
      
spring:
  application:
   name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microUSERservice
    username: root
    password: Sachin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:globally_quoted_identifiers=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  cloud:
   config:
    enabled: false
  




